- name: GIT | clone DPDK repo
  ansible.builtin.git:
    repo: https://github.com/DPDK/dpdk.git
    dest: "{{ dpdk_src_dir }}"
    version: "{{ dpdk_branch }}"

- name: BLOCK
  block:
  - name: BUILD | build DPDK
    shell: |
      source /root/.bashrc
      meson -Dexamples=all -Dbuildtype=debug -Dplatform=native build --prefix=/usr/
    args:
      chdir: "{{ dpdk_src_dir }}"
      creates: "{{ dpdk_src_dir }}/build"
      executable: /bin/bash
    register: dpkg_build_result

  - name: INSTALL | install DPDK
    shell: |
      source /root/.bashrc
      ninja install
    args:
      chdir: "{{ dpdk_src_dir }}/build"
      #creates: "{{ dpdk_src_dir }}/build"
      executable: /bin/bash
    when: dpkg_build_result.changed
    async: 900
    poll: 10

  rescue:
  - fail:  # FIXME
  - name: CLEAN | clean DPDK build if failed
    file:
      path: "{{ dpdk_src_dir }}/build"
      state: absent

  - name: FAIL
    fail:
      msg: "{{ dpkg_build_result }}"

- name: LDCONFIG | update shared libs
  ansible.builtin.command: ldconfig
  when: dpkg_build_result.changed
