- name: GIT | clone DPDK repo
  ansible.builtin.git:
    repo: https://github.com/DPDK/dpdk.git
    dest: /root/dpdk
    version: "{{ dpdk_branch }}"

- name: BLOCK
  block:
  - name: BUILD | build DPDK
    shell: |
      source /root/.bashrc
      meson -Dexamples=all -Dbuildtype=debug -Dplatform=native build --prefix=/usr/
    args:
      chdir: /root/dpdk
      creates: /root/dpdk/build
      executable: /bin/bash
    register: dpkg_build_result

  rescue:
  - name: CLEAN | clean DPDK build if failed
    file:
      path: /root/dpdk/build
      state: absent

  - name: FAIL
    fail:
      msg: "{{ dpkg_build_result }}"

- name: LDCONFIG | update shared libs
  ansible.builtin.command: ldconfig
  when: dpkg_build_result.changed
